fixed positioning

diff --git a/paperWiz b/paperWiz
--- a/paperWiz
+++ b/paperWiz
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -x
+
 # Set your desired resolution here
 resW=2560
 resH=1440
@@ -77,12 +79,17 @@ if (( ${walColor} < -1 || ${walColor} > 15 )); then
 fi
 
 # Set and check the position variable
-position_map=(["c"]="center" ["n"]="north" ["s"]="south" ["w"]="west" ["e"]="east")
-position=${position_map[${position}]:-}
-if [ -z "$position" ]; then
-	echo "Error: The position specified must be c, s, n, w, or e" >&2
-	exit 1
-fi
+case "$position" in
+  "c") position="center" ;;
+  "n") position="north" ;;
+  "s") position="south" ;;
+  "e") position="east" ;;
+  "w") position="west" ;;
+  *)
+    echo "Error: The position specified must be c, s, n, w, or e" >&2
+    exit 1
+    ;;
+esac
 
 # Set wallpaper and theme programs
 {
